import type { Agent } from "../lib/departments";
import { useState, useEffect, useRef, useCallback } from "react";
import {
  CheckCircle2,
  Loader2,
  Clock,
  AlertCircle,
  Copy,
  Check,
  Download,
  ChevronDown,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { jsPDF } from "jspdf";

interface AgentCardProps {
  agent: Agent;
  departmentColor: string;
  status?: "idle" | "working" | "completed" | "failed";
  output?: string | null;
  index: number;
}

function generatePdfFilename(agentName: string): string {
  const date = new Date().toISOString().slice(0, 10);
  const slug = agentName.toLowerCase().replace(/\s+/g, "-");
  return `${slug}-output-${date}.pdf`;
}

function markdownToPlainText(md: string): string {
  return md
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`(.+?)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^[-*+]\s+/gm, "• ")
    .replace(/^\d+\.\s+/gm, (match) => match)
    .replace(/\|/g, " ")
    .replace(/^---+/gm, "─".repeat(40))
    .trim();
}

export default function AgentCard({
  agent,
  departmentColor,
  status = "idle",
  output,
  index,
}: AgentCardProps) {
  const [visible, setVisible] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  const [pdfGenerating, setPdfGenerating] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  // Stagger entrance animation
  useEffect(() => {
    const timer = setTimeout(() => setVisible(true), index * 100);
    return () => clearTimeout(timer);
  }, [index]);

  // Auto-expand when output arrives
  useEffect(() => {
    if (output && status === "completed") {
      setExpanded(true);
    }
  }, [output, status]);

  const handleCopy = useCallback(async () => {
    if (!output) return;
    const plainText = markdownToPlainText(output);
    try {
      await navigator.clipboard.writeText(plainText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = plainText;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [output]);

  const handleDownloadPdf = useCallback(async () => {
    if (!output) return;
    setPdfGenerating(true);

    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 50;
    const contentWidth = pageWidth - margin * 2;
    const title = `${agent.name} — ${agent.role}`;
    const plainText = markdownToPlainText(output);

    // Title
    doc.setFontSize(16);
    doc.setTextColor(30, 30, 40);
    doc.text(title, margin, 60, { maxWidth: contentWidth });

    // Separator line
    doc.setDrawColor(200, 200, 210);
    doc.line(margin, 75, pageWidth - margin, 75);

    // Metadata
    doc.setFontSize(9);
    doc.setTextColor(130, 130, 140);
    doc.text(`Generated by ForgeOS • ${new Date().toLocaleDateString()}`, margin, 95);

    // Body text
    doc.setFontSize(10.5);
    doc.setTextColor(50, 50, 60);

    const lines = doc.splitTextToSize(plainText, contentWidth);
    let y = 120;

    for (const line of lines) {
      // Check for page break
      if (y > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = 60;
      }

      // Style headings (lines starting with common heading patterns or all-caps)
      const trimmed = line.trim();
      if (
        trimmed.match(/^[A-Z][A-Z\s]+$/) && trimmed.length < 60 ||
        trimmed.match(/^(Executive|Strategic|Creative|Technical|Key|Primary|Recommended)/)
      ) {
        doc.setFontSize(12);
        doc.setTextColor(30, 30, 40);
        doc.text(trimmed, margin, y);
        doc.setFontSize(10.5);
        doc.setTextColor(50, 50, 60);
        y += 22;
      } else if (trimmed.startsWith("•")) {
        doc.text(trimmed, margin + 12, y);
        y += 16;
      } else if (trimmed === "─".repeat(40)) {
        y += 10;
      } else if (trimmed === "") {
        y += 10;
      } else {
        doc.text(trimmed, margin, y, { maxWidth: contentWidth });
        y += 16;
      }
    }

    doc.save(generatePdfFilename(agent.name));
    setPdfGenerating(false);
  }, [output, agent]);

  const statusConfig = {
    idle: {
      icon: Clock,
      className: "text-subtle",
      bg: "bg-elevated",
      label: "Idle",
    },
    working: {
      icon: Loader2,
      className: "text-[var(--dept-color)] animate-spin",
      bg: "bg-elevated",
      label: "Working...",
    },
    completed: {
      icon: CheckCircle2,
      className: "text-success",
      bg: "bg-success/10",
      label: "Done",
    },
    failed: {
      icon: AlertCircle,
      className: "text-error",
      bg: "bg-error/10",
      label: "Failed",
    },
  };

  const { icon: StatusIcon, className: statusClass, bg, label } =
    statusConfig[status];

  const hasOutput = !!output && status === "completed";

  return (
    <div
      className={`rounded-xl bg-surface border transition-all duration-500 ${
        visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
      } ${
        status === "working"
          ? "agent-working border-[var(--dept-color)]"
          : status === "completed"
          ? "border-success/30"
          : "border-border"
      }`}
      style={{ "--dept-color": departmentColor } as React.CSSProperties}
    >
      {/* Header — always visible, acts as the collapsible trigger */}
      <button
        type="button"
        onClick={() => setExpanded((prev) => !prev)}
        className="w-full flex items-center gap-3 p-5 text-left cursor-pointer focus:outline-2 focus:outline-offset-[-2px] focus:outline-[var(--dept-color)] rounded-xl"
        aria-expanded={expanded}
        aria-controls={`agent-output-${agent.id}`}
      >
        {/* Avatar */}
        <div
          className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 text-sm font-bold font-mono"
          style={{
            background: `${departmentColor}18`,
            color: departmentColor,
          }}
        >
          {agent.avatar_letter}
        </div>

        {/* Name + role */}
        <div className="flex-1 min-w-0">
          <h4 className="font-medium text-foreground text-sm truncate">
            {agent.name}
          </h4>
          <p className="text-xs text-muted truncate">{agent.role}</p>
        </div>

        {/* Status badge */}
        <div
          className={`flex items-center gap-1 px-2 py-1 rounded-full text-xs ${bg}`}
        >
          <StatusIcon size={12} className={statusClass} />
          <span
            className={
              status === "working" ? "text-[var(--dept-color)]" : "text-muted"
            }
          >
            {label}
          </span>
        </div>

        {/* Expand chevron */}
        {hasOutput && (
          <ChevronDown
            size={16}
            className={`text-subtle transition-transform duration-300 flex-shrink-0 ${
              expanded ? "rotate-180" : ""
            }`}
          />
        )}
      </button>

      {/* Collapsible output content */}
      {hasOutput && expanded && (
        <div
          id={`agent-output-${agent.id}`}
          ref={contentRef}
          className="px-5 pb-5"
        >
          {/* Action buttons */}
          <div className="flex items-center gap-2 mb-4">
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                handleCopy();
              }}
              disabled={copied}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all duration-150 active:scale-95 cursor-pointer ${
                copied
                  ? "bg-success/10 text-success border border-success/30"
                  : "bg-elevated text-muted hover:text-foreground border border-border hover:border-subtle"
              }`}
              aria-label={copied ? "Copied to clipboard" : "Copy output to clipboard"}
            >
              {copied ? (
                <>
                  <Check size={13} aria-hidden="true" />
                  Copied
                </>
              ) : (
                <>
                  <Copy size={13} aria-hidden="true" />
                  Copy
                </>
              )}
            </button>

            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                handleDownloadPdf();
              }}
              disabled={pdfGenerating}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-elevated text-muted hover:text-foreground border border-border hover:border-subtle transition-all duration-150 active:scale-95 cursor-pointer disabled:opacity-50"
              aria-label="Download output as PDF"
            >
              <Download size={13} aria-hidden="true" />
              {pdfGenerating ? "Generating…" : "PDF"}
            </button>
          </div>

          {/* Rendered markdown content */}
          <div className="markdown-content p-4 rounded-lg bg-elevated border border-border text-sm text-foreground leading-relaxed max-h-[500px] overflow-y-auto">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {output}
            </ReactMarkdown>
          </div>
        </div>
      )}

      {/* Loading skeleton */}
      {status === "working" && !output && (
        <div className="px-5 pb-5 space-y-2">
          <div className="h-3 bg-elevated rounded animate-shimmer" />
          <div className="h-3 bg-elevated rounded animate-shimmer w-3/4" />
          <div className="h-3 bg-elevated rounded animate-shimmer w-1/2" />
        </div>
      )}

      {/* Idle placeholder */}
      {status === "idle" && (
        <div className="px-5 pb-5">
          <p className="text-xs text-muted italic">
            Waiting for task to begin…
          </p>
        </div>
      )}

      {/* Failed state */}
      {status === "failed" && (
        <div className="px-5 pb-5">
          <p className="text-xs text-error">
            This agent encountered an error. Try resubmitting the task.
          </p>
        </div>
      )}
    </div>
  );
}
